name       : perl-module-runtime
version    : 0.014
release    : 2
source     :
    - http://search.cpan.org/CPAN/authors/id/Z/ZE/ZEFRAM/Module-Runtime-0.014.tar.gz : 4c44fe0ea255a9fd00741ee545063f6692d2a28e7ef2fbaad1b24a92803362a4
license    : GPL-2.0
component  : programming.perl
summary    : The functions exported by this module deal with runtime handling of Perl
    modules, which are normally handled at compile time
description: |
    The functions exported by this module deal with runtime handling of Perl modules, which are normally handled at compile time
builddeps  :
    - perl-module-build
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
