name       : perl-module-runtime
version    : '0.016'
release    : 9
source     :
    - https://cpan.metacpan.org/authors/id/Z/ZE/ZEFRAM/Module-Runtime-0.016.tar.gz : 68302ec646833547d410be28e09676db75006f4aa58a11f3bdb44ffe99f0f024
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Module::Runtime - runtime module handling
description: |
    The functions exported by this module deal with runtime handling of Perl modules, which are normally handled at compile time
builddeps  :
    - perl-module-build
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
